import { ClerkProvider } from '@clerk/nextjs'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body style={{ margin: 0, padding: 0, overflow: 'hidden' }}>{children}</body>
      </html>
    </ClerkProvider>
  )
}
